import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomProviders from "./store/CustomProviders";
import Header from "./components/headers";
import ProtectedRoute from "./components/protectedRoutes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomProviders>
          <Header />
          <ProtectedRoute>
            <main className="flex-grow p-8 pb-20 mt-[60px] h-[90vh] left-0 right-0 bottom-0">
              {children}
            </main>
          </ProtectedRoute>
        </CustomProviders>
      </body>
    </html>
  );
}
